version: 2.1

jobs: 
  yarn: 
    docker: 
      - image: cimg/node:12.18
    steps: 
      - checkout
      - restore_cache:
          key: npm-v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp && yarn install
      - run: yarn build

      - save_cache:
          key: npm-v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

workflows:
  node-tests:
    jobs:
      - yarn